### PR TITLE
ctags is a virtual package

### PR DESCRIPTION
**Pull request by elgalu**
Chef::Exceptions::Package
-------------------------
ctags is a virtual package provided by 2 packages, you must explicitly select one to install

### CODE REVIEW

**Comment by tas50** [comment]
@elgalu What would be the appropriate package to install then?

**Comment by elgalu** [comment]
I don't remember much of this (18 months ago) but I think this PR avoids the failure and allows to keep going, and vim gets installed. But feel free to close this as it is so old, the issue might not be even there anymore.

**Comment by promisedlandt** [comment]
Pretty sure this is still an issue. The appropriate package to install is exuberant-ctags. It gets auto-selected on Debian (newer versions at least) when you try to install ctags, but Ubuntu users are not so lucky.

**Comment by tas50** [comment]
I've fixed this in master

**Pull request closed without merging**
